[package]
name = "recolor-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
clap = { version = "4", features = ["derive"] }
viuer = { version = "0.9.2", features = [ "print-file"] }

